title: Javad Mazyar
description:  Javad Mazyar online resume
url: https://jmazyar.github.io/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml

theme: jekyll-theme-minimal